In [1]:
import numpy as np
a = np.arange(5) #1D Array
print(a)

[0 1 2 3 4]


In [2]:
a.shape #Dimension of array

(5,)

In [8]:
b = np.arange(15).reshape(5,3) #2D Array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [9]:
b.shape

(5, 3)

In [12]:
c = np.arange(40).reshape(2,4,5) #3D Array
print(c)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [15]:
d = np.array([15,15,15])  #arithmetic operations
e = np.array([10,10,10])

In [16]:
d+e 

array([25, 25, 25])

In [17]:
d-e

array([5, 5, 5])

In [18]:
d/e

array([1.5, 1.5, 1.5])

In [19]:
d<20

array([ True,  True,  True])

In [20]:
e>15

array([False, False, False])

In [21]:
d**2 #power operation

array([225, 225, 225], dtype=int32)

In [22]:
e**3

array([1000, 1000, 1000], dtype=int32)

In [26]:
d*=4
d

array([60, 60, 60])

In [27]:
print(d)

[60 60 60]


In [30]:
d+=e
d

array([90, 90, 90])

In [31]:
print(d)

[90 90 90]


In [32]:
j = np.array([12,56,78,23,54])

In [33]:
j.sum()

223

In [34]:
j.min()

12

In [35]:
j.max()

78

In [36]:
num = np.arange(12).reshape(3,4)
num

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
num.sum(axis = 1) #sum of columns

array([ 6, 22, 38])

In [38]:
num.sum(axis = 0) #sum of rows

array([12, 15, 18, 21])