In [1]:
import numpy as np #displaying numpy array
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [2]:
type(arr) #type of array

numpy.ndarray

In [3]:
import numpy as np
arr = np.array((1,2,3,4))
arr

array([1, 2, 3, 4])

In [10]:
import numpy as np #array of ones with float output
arr_of_ones = np.ones((3,4))
arr_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
arr_of_ones = np.ones((3,4),dtype=np.int16)#array of ones with int output
arr_of_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [14]:
arr_empty = np.empty((2,3))
arr_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
array_eye = np.eye(4) #identity matrix
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
arr_even = np.arange(2,50,2) #even numbers
arr_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [19]:
arr_odd = np.arange(1,50,2) #odd numbers
arr_odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [20]:
arr_of_zeros = np.zeros((3,4)) #array of zeros
arr_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])